name: Test Suite

on:
  push:
    branches: [ main, develop, epic/* ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: word-plugin/package-lock.json

    - name: Install dependencies
      working-directory: ./word-plugin
      run: npm ci

    - name: Run tests
      working-directory: ./word-plugin
      run: npm run test:ci

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      if: matrix.node-version == '20.x'
      with:
        files: ./word-plugin/coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

    - name: Archive coverage report
      if: matrix.node-version == '20.x'
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: word-plugin/coverage/
        retention-days: 30
